DiamondLightSource/cryoem-services

Dockerfiles/cryoemservices_cpu, src/cryoemservices/services/tomo_align_slurm.py, tests/services/test_tomo_align_slurm.py
The datasyncer for IRIS has caused problems in the past so I suggest we stop using it for now. The only downside is slower transfer.
Currently the file transfer is quite specific to the DLS/IRIS setup, but in future may be generalisable.
=> Remove need for datasyncer

.github/workflows/publish-version.yml, .github/workflows/test.yml, .github/workflows/version-bump.yml, Dockerfiles/class_selection, Dockerfiles/cryoemservices_cpu, Dockerfiles/cryolo, Dockerfiles/ctffind, Dockerfiles/motioncor2, Dockerfiles/motioncor_relion, Dockerfiles/tomo_align, Dockerfiles/topaz, pyproject.toml, src/cryoemservices/services/node_creator.py
Remove support for python 3.9, and add support for 3.12. All automated actions and dockerfiles are upgraded to 3.11.
Most of this commit consists of Dockerfile updates. These move to 3.11 and Miniforge, but also have some rearrangements as they were out-of-date.
To get Relion's class selection to work in python>3.9 has required moving to Relion 5.0, with a corresponding branch on the fork at https://github.com/d-j-hatton/relion/tree/ver5.0-mc-devolve
The ccpem-pipeliner fork we use at https://gitlab.com/stephen-riggs/ccpem-pipeliner/-/tree/diamond_tomo has also been updated. However, not all the dependencies work in python 3.12, so these have had to be removed temporarily.
=> Upgrade supported python versions to 3.10/3.11/3.12

src/cryoemservices/services/tomo_align.py, tests/services/test_tomo_align.py
If a tilt angle was repeated for a tomogram, the code to exclude all but the most recent tilt did not work as expected.
This fixes that, and adds a test for it.
=> Fix the logic for handling duplicated tilt angles

Dockerfiles/ctffind, src/cryoemservices/services/ctffind.py, tests/services/test_ctffind_service.py
We now have a working version of CTFFind5 so this updates the service to be compatible with version 4 or 5. For compatibility I've chosen to rename the executable as "ctffind5" for version 5 but keep it as "ctffind" for version 4.
Relion does not currently support version 5 though, so we may want to stick with using 4 at the moment.
Addresses another part of #10
=> Allow the use of CTFFind5

Helm/charts/bfactor_setup/templates/deployment.yaml, Helm/charts/cluster_submission/templates/deployment.yaml, Helm/charts/cryolo/templates/deployment.yaml, Helm/charts/ctffind/templates/deployment.yaml, Helm/charts/denoise/templates/deployment.yaml, Helm/charts/denoise_slurm/templates/deployment.yaml, Helm/charts/extract/templates/deployment.yaml, Helm/charts/extract_class/templates/deployment.yaml, Helm/charts/icebreaker/templates/deployment.yaml, Helm/charts/images/templates/deployment.yaml, Helm/charts/ispyb_connector/templates/deployment.yaml, Helm/charts/membrain_seg/templates/deployment.yaml, Helm/charts/motioncorr/templates/deployment.yaml, Helm/charts/node_creator/templates/deployment.yaml, Helm/charts/postprocess/templates/deployment.yaml, Helm/charts/process_recipe/templates/deployment.yaml, Helm/charts/select_classes/templates/deployment.yaml, Helm/charts/select_particles/templates/deployment.yaml, Helm/charts/tomo_align/templates/deployment.yaml, Helm/charts/tomo_align_slurm/templates/deployment.yaml, Helm/values.yaml
Now that the zocalo config file has been removed, the rmq api secret can be merged with the main rmq secret
=> Remove rmq api secret references

src/cryoemservices/services/ispyb_connector.py, src/cryoemservices/util/ispyb_commands.py, tests/services/test_ispyb_service.py, tests/util/test_ispyb_commands.py
Addresses a few issues that have cropped up:
- Messages should be nacked if they timeout, rather than checkpointing. In future we may want to re-introduce some checkpointing
- Foil hole ID cannot be string "None"
- Particle pick count should be 0 rather than NULL
- Dollar lookup keys can be present in nested calls. The solution for this is to check these in the nested stages and retrieve them from the parameters function if needed. This isn't a nice method, but it works for now.
=> Various fixes to ispyb inserts

src/cryoemservices/cli/start_service.py, src/cryoemservices/services/bfactor_setup.py, src/cryoemservices/services/cluster_submission.py, src/cryoemservices/services/cryolo.py, src/cryoemservices/services/ctffind.py, src/cryoemservices/services/denoise.py, src/cryoemservices/services/extract.py, src/cryoemservices/services/extract_class.py, src/cryoemservices/services/icebreaker.py, src/cryoemservices/services/images.py, src/cryoemservices/services/ispyb_connector.py, src/cryoemservices/services/membrain_seg.py, src/cryoemservices/services/motioncorr.py, src/cryoemservices/services/node_creator.py, src/cryoemservices/services/postprocess.py, src/cryoemservices/services/process_recipe.py, src/cryoemservices/services/select_classes.py, src/cryoemservices/services/select_particles.py, src/cryoemservices/services/tomo_align.py, tests/cli/test_start_service.py
This is needed to run the same service from multiple queues:
- Currently we have several node creator queues
- Desirable to run separate CPU and GPU versions of cryolo
=> Add an option to override the default queue used by the services

Helm/Chart.yaml, Helm/charts/cryolo_gpu/Chart.yaml, Helm/charts/cryolo_gpu/templates/deployment.yaml, Helm/values.yaml, recipes/em-tomo-align.json, src/cryoemservices/services/cryolo.py, tests/services/test_bfactor_setup.py, tests/services/test_cluster_submission.py, tests/services/test_cryolo_service.py, tests/services/test_ctffind_service.py, tests/services/test_denoise.py, tests/services/test_extract_class.py, tests/services/test_extract_service.py, tests/services/test_icebreaker_service.py, tests/services/test_ispyb_service.py, tests/services/test_membrain_seg.py, tests/services/test_motioncorr_service.py, tests/services/test_node_creator.py, tests/services/test_postprocess.py, tests/services/test_process_recipe.py, tests/services/test_select_classes_service.py, tests/services/test_select_particles_service.py, tests/services/test_tomo_align.py, tests/services/test_tomo_align_slurm.py
Cryolo is too slow on CPU for tomography, so we need to switch to GPU.
This adds the helm chart parts needed to have a separate GPU cryolo service running for tomography.
To allow the service to connect to different queues for SPA and tomography, the service startup command must accept a  queue name to override the default for the service. (see #111)
=> Add a GPU version of cryolo for tomography processing

src/cryoemservices/cli/resubmit_wrapper.py, tests/cli/test_resubmit_wrapper.py
The wrapper resubmission cli was using a different `-c` argument from all the other cli commands.
This changes it to match the other clis, and also adds some tests for it.
=> Change config file for wrapper resubmission

src/cryoemservices/services/cryolo.py, src/cryoemservices/services/images.py, src/cryoemservices/services/images_plugins.py, tests/services/test_cryolo_service.py, tests/services/test_images_plugins.py, tests/services/test_images_service.py
For tomography, previously the sizes of tomography particles were plotted using the box size given to cryolo. However, the CBOX output files contains the true widths and heights, plus the number of frames and particles appear in. The changes here mean the values in the CBOX are used.
This also cleans up the images plugins, dropping the `PluginInterface` which contained usused attributes, and adding checks that any required parameters are present.
=> Plot the true particles sizes for tomography

src/cryoemservices/services/tomo_align.py, src/cryoemservices/util/tomo_output_files.py, tests/services/test_tomo_align.py
Relion's motion correction sometimes fails on local alignment and produces abstract images. These then get put into tomogram alignment and disrupt the outputs.
The only way I can readily see to avoid this is to check the star files written out by Relion. 
Firstly, we need to check if the file exists, then if the local motion model was used, and finally when coefficients were found.
I've put a threshold of 1000 on the local alignment coefficients, but this is an arbitrary choice.
This will result in an increase in I/O and maybe slow down alignment slightly.
=> Exclude images with bad motion correction results from tomogram alignment

Dockerfiles/cryolo, README.md, pyproject.toml, recipes/clem-align-and-merge.json, recipes/clem-lif-to-stack.json, recipes/clem-tiff-to-stack.json, recipes/em-spa-bfactor.json, recipes/em-spa-class2d.json, recipes/em-spa-class3d.json, recipes/em-spa-refine.json, src/cryoemservices/cli/dlq_rabbitmq.py, src/cryoemservices/cli/run_wrapper.py, src/cryoemservices/services/cluster_submission.py, src/cryoemservices/wrappers/class2d_wrapper.py, src/cryoemservices/wrappers/class3d_wrapper.py, src/cryoemservices/wrappers/clem_align_and_merge.py, src/cryoemservices/wrappers/clem_process_raw_lifs.py, src/cryoemservices/wrappers/clem_process_raw_tiffs.py, src/cryoemservices/wrappers/refine3d_wrapper.py, tests/cli/test_dlq_rabbitmq.py, tests/cli/test_run_wrapper.py, tests/services/test_cluster_submission.py, tests/wrappers/test_class2d_wrapper.py, tests/wrappers/test_class3d_wrapper.py, tests/wrappers/test_clem_align_and_merge.py, tests/wrappers/test_clem_process_raw_lifs.py, tests/wrappers/test_clem_process_raw_tiffs.py, tests/wrappers/test_refine3d_wrapper.py
The dependency on zocalo is not needed now, as we were just importing a few classes which we don't need many of the attributes from. This adds what we need of them to this repo, so we can remove the dependency.
One complication which needs addressing in future is we still have an ex-zocalo `cluster_submission.py` service as well as a `slurm_submission.py` which other services access.
=> Completely remove the zocalo package dependency

pyproject.toml, src/cryoemservices/pipeliner_plugins/angular_efficiency.py, src/cryoemservices/wrappers/class3d_wrapper.py, tests/pipeliner_plugins/test_angular_efficiency.py, tests/wrappers/test_class3d_wrapper.py
This implements the efficiency part of `cryoEF` using python, without the loop over particles which makes the original C code so slow.
For now, the efficiency is just requested by Class3D and logged as we cannot record into ispyb yet.
When deciding whether to refine, the logic is now:
- best resolution
- or best efficiency
- or lowest particle count
The fourier completeness threshold of 0.9 has been replaced with an efficiency threshold of 0.65
=> Add code to calculate the efficiency of angular distributions

src/cryoemservices/services/cryolo.py, tests/services/test_cryolo_service.py
The PR at https://github.com/DiamondLightSource/python-murfey/pull/484 looks for parameters named `particle_count`, `astigmatism`, `defocus`, and `resolution` in the messages received by the feedback queue, and these values appear to be calculated as part of the CTFFind service, but are not passed on back to Murfey.
This PR adds those values to the message sent by the Cryolo service back to Murfey.
=> Added values used by Murfey's email notification workflow to the message sent back from cryolo

src/cryoemservices/services/images_plugins.py, src/cryoemservices/services/motioncorr.py, src/cryoemservices/services/tomo_align.py, tests/services/test_images_plugins.py, tests/services/test_tomo_align.py
On the talos we had orientation issues with the tomograms due to a tilt axis of zero (previously it was assumed the axis was around 90). This adds a fix for the zero case.
Also removes the edge effect on 3D apngs which we no longer need
=> Rotate the tomograms differently if the tilt axis is zero

src/cryoemservices/services/images.py, src/cryoemservices/services/images_plugins.py, tests/services/test_images_plugins.py, tests/services/test_images_service.py
A previous change resulted in some apng images not being of uint8 format, which displayed wrong.
This corrects that, and also allows the images service to take in simple messages.
=> Fix scaling of apng images

src/cryoemservices/services/cryolo.py, src/cryoemservices/services/images_plugins.py, src/cryoemservices/services/select_classes.py, tests/services/test_images_plugins.py, tests/services/test_select_classes_service.py
The class selection service has to process too many images for it to be viable to run the flattening in there.
This instead gets the images service to do it.
=> Do not flatten picked images in the class selection service

src/cryoemservices/pipeliner_plugins/combine_star_files.py, src/cryoemservices/services/select_classes.py, tests/services/test_select_classes_service.py
Murfey always needs a class selection score to flush 2D classification. The score no longer corresponds with selected particles, but this sends the score from the Relion class selection anyway.
Also the last key in the particle batch files was duplicated, due to an issue with line counting, which is fixed here.
=> Cryodann particles selection fixes

src/cryoemservices/services/node_creator.py, src/cryoemservices/services/tomo_align.py, src/cryoemservices/util/tomo_output_files.py, tests/services/test_node_creator.py, tests/services/test_tomo_align.py
We're not currently matching relion 5 in all the tomography star files. This addresses some issues, although there may be more to find.
- Input to ExcludeTiltSeries should be CtfFind
- ExcludeTiltSeries jobs should have CTF outputs in the tilt series star files
- If CTF output does not exist, do not make star files (in future we could include ctf directly in the workflow to ensure this is true)
- Inputs will be relative to /.../project/MotionCorr, not just MotionCorr
=> Adjustments to star files written by tomography

src/cryoemservices/util/tomo_output_files.py, tests/services/test_node_creator.py
Relion particle extraction failed to recognise the particle positions when un-centered in the tomogram. This applies the centering and unit conversion to the `particles.star` file made after picking.
Doing this requires more of the `relion_options` to be set. These *should* be set by the `tomo_align` service prior to picking, but they could be passed into picking as inputs if we wanted to be more sure of them being set.
These coordinate corrections appear to work for tomograms without a pre-tilt. The case of a pre-tilt is still to be investigated but these changes are useful enough to go in now anyway.
=> Coordinate corrections for tomograms

src/cryoemservices/services/denoise.py, src/cryoemservices/services/membrain_seg.py, src/cryoemservices/services/tomo_align.py, src/cryoemservices/util/tomo_output_files.py, tests/services/test_denoise.py, tests/services/test_membrain_seg.py, tests/services/test_node_creator.py, tests/services/test_tomo_align.py
In the existing setup, if a tomogram is processed twice it will get inserted into star files twice. This resolves that and provides only a single insert.
For tomograms, denoising and segmentation this is as simple as not re-sending the node creator request.
For alignment parameters and picks we need to first remove the existing values from the star files, then add in the new values instead.
=> Tomogram re-run star file fixes
